import type { Mascota } from "@/app/types/types"

export const MASCOTAS_INICIALES: Mascota[] = [
  {
    id: "p1",
    nombre: "Firulais",
    especie: "perro",
    raza: "Labrador",
    edad: 4,
    owner: "Marcela Pérez",
    telefono: "+56 9 1234 5678",
    notas: "Alérgico a la penicilina",
    fecha_registro: "2026-01-15",
  },
  {
    id: "p2",
    nombre: "Michi",
    especie: "gato",
    raza: "Mestizo",
    edad: 2,
    owner: "Joaquín Reyes",
    telefono: "+56 9 8765 4321",
    notas: "",
    fecha_registro: "2026-02-03",
  },
  {
    id: "p3",
    nombre: "Rocky",
    especie: "perro",
    raza: "Bulldog Francés",
    edad: 6,
    owner: "Andrea Soto",
    telefono: "+56 9 5555 1212",
    notas: "Problemas respiratorios, evitar ejercicio intenso",
    fecha_registro: "2026-03-10",
  },
  {
    id: "p4",
    nombre: "Luna",
    especie: "gato",
    raza: "Mestizo",
    edad: 8,
    owner: "Sofía Méndez",
    telefono: "+56 9 7777 8888",
    notas: "Requiere alimento especial para control renal",
    fecha_registro: "2026-06-01",
  },
  {
    id: "p5",
    nombre: "Thor",
    especie: "perro",
    raza: "Pastor Alemán",
    edad: 3,
    owner: "Carlos Valenzuela",
    telefono: "+56 9 9999 0000",
    notas: "Padece displasia de cadera leve",
    fecha_registro: "2026-06-15",
  }
]
